index:
    path: /
    controller: App\Controller\PinsController::index
create:
    path: /create
    controller: App\Controller\PinsController::create
show:
    path: /pins/{id}
    controller: App\Controller\PinsController::show
edit:
    path: /pins/edit/{id}
    controller: App\Controller\PinsController::edit
